/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as DemoClerkRouteImport } from './routes/demo/clerk'
import { Route as DemoPrismaRouteImport } from './routes/demo/prisma'
import { Route as AdminSeasonsIndexRouteImport } from './routes/admin/seasons/index'
import { Route as AdminSeasonsSeasonIdRouteImport } from './routes/admin/seasons/$seasonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoClerkRoute = DemoClerkRouteImport.update({
  id: '/demo/clerk',
  path: '/demo/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoPrismaRoute = DemoPrismaRouteImport.update({
  id: '/demo/prisma',
  path: '/demo/prisma',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSeasonsIndexRoute = AdminSeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeasonsSeasonIdRoute = AdminSeasonsSeasonIdRouteImport.update({
  id: '/seasons/$seasonId',
  path: '/seasons/$seasonId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons': typeof AdminSeasonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/seasons': typeof SeasonsRoute
  '/demo/clerk': typeof DemoClerkRoute
  '/demo/prisma': typeof DemoPrismaRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/seasons'
    | '/demo/clerk'
    | '/demo/prisma'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/seasons'
    | '/demo/clerk'
    | '/demo/prisma'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/seasons'
    | '/demo/clerk'
    | '/demo/prisma'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  SeasonsRoute: typeof SeasonsRoute
  DemoClerkRoute: typeof DemoClerkRoute
  DemoPrismaRoute: typeof DemoPrismaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/clerk': {
      id: '/demo/clerk'
      path: '/demo/clerk'
      fullPath: '/demo/clerk'
      preLoaderRoute: typeof DemoClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/prisma': {
      id: '/demo/prisma'
      path: '/demo/prisma'
      fullPath: '/demo/prisma'
      preLoaderRoute: typeof DemoPrismaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/seasons/': {
      id: '/admin/seasons/'
      path: '/seasons'
      fullPath: '/admin/seasons/'
      preLoaderRoute: typeof AdminSeasonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seasons/$seasonId': {
      id: '/admin/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/admin/seasons/$seasonId'
      preLoaderRoute: typeof AdminSeasonsSeasonIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSeasonsSeasonIdRoute: typeof AdminSeasonsSeasonIdRoute
  AdminSeasonsIndexRoute: typeof AdminSeasonsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSeasonsSeasonIdRoute: AdminSeasonsSeasonIdRoute,
  AdminSeasonsIndexRoute: AdminSeasonsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  SeasonsRoute: SeasonsRoute,
  DemoClerkRoute: DemoClerkRoute,
  DemoPrismaRoute: DemoPrismaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
