/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SeasonsRouteImport } from './routes/seasons'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SeasonsSeasonIdRouteImport } from './routes/seasons/$seasonId'
import { Route as AdminSeasonsIndexRouteImport } from './routes/admin/seasons/index'
import { Route as AdminSeasonsSeasonIdRouteImport } from './routes/admin/seasons/$seasonId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsRoute = SeasonsRouteImport.update({
  id: '/seasons',
  path: '/seasons',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SeasonsSeasonIdRoute = SeasonsSeasonIdRouteImport.update({
  id: '/$seasonId',
  path: '/$seasonId',
  getParentRoute: () => SeasonsRoute,
} as any)
const AdminSeasonsIndexRoute = AdminSeasonsIndexRouteImport.update({
  id: '/seasons/',
  path: '/seasons/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSeasonsSeasonIdRoute = AdminSeasonsSeasonIdRouteImport.update({
  id: '/seasons/$seasonId',
  path: '/seasons/$seasonId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons': typeof AdminSeasonsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/robots.txt': typeof RobotsDottxtRoute
  '/seasons': typeof SeasonsRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/seasons/$seasonId': typeof SeasonsSeasonIdRoute
  '/admin/seasons/$seasonId': typeof AdminSeasonsSeasonIdRoute
  '/admin/seasons/': typeof AdminSeasonsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/seasons'
    | '/sitemap.xml'
    | '/seasons/$seasonId'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/seasons'
    | '/sitemap.xml'
    | '/seasons/$seasonId'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/robots.txt'
    | '/seasons'
    | '/sitemap.xml'
    | '/seasons/$seasonId'
    | '/admin/seasons/$seasonId'
    | '/admin/seasons/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SeasonsRoute: typeof SeasonsRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons': {
      id: '/seasons'
      path: '/seasons'
      fullPath: '/seasons'
      preLoaderRoute: typeof SeasonsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/seasons/$seasonId': {
      id: '/seasons/$seasonId'
      path: '/$seasonId'
      fullPath: '/seasons/$seasonId'
      preLoaderRoute: typeof SeasonsSeasonIdRouteImport
      parentRoute: typeof SeasonsRoute
    }
    '/admin/seasons/': {
      id: '/admin/seasons/'
      path: '/seasons'
      fullPath: '/admin/seasons/'
      preLoaderRoute: typeof AdminSeasonsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/seasons/$seasonId': {
      id: '/admin/seasons/$seasonId'
      path: '/seasons/$seasonId'
      fullPath: '/admin/seasons/$seasonId'
      preLoaderRoute: typeof AdminSeasonsSeasonIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminSeasonsSeasonIdRoute: typeof AdminSeasonsSeasonIdRoute
  AdminSeasonsIndexRoute: typeof AdminSeasonsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSeasonsSeasonIdRoute: AdminSeasonsSeasonIdRoute,
  AdminSeasonsIndexRoute: AdminSeasonsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface SeasonsRouteChildren {
  SeasonsSeasonIdRoute: typeof SeasonsSeasonIdRoute
}

const SeasonsRouteChildren: SeasonsRouteChildren = {
  SeasonsSeasonIdRoute: SeasonsSeasonIdRoute,
}

const SeasonsRouteWithChildren =
  SeasonsRoute._addFileChildren(SeasonsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SeasonsRoute: SeasonsRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
